# Generated by Django 5.0.1 on 2024-01-30 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelGuru',
            fields=[
                ('id_guru', models.AutoField(primary_key=True, serialize=False)),
                ('nip', models.CharField(max_length=255)),
                ('nama_guru', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('tempat_lahir', models.CharField(max_length=255)),
                ('tanggal_lahir', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelJenjangKelas',
            fields=[
                ('id_jenjang_kelas', models.AutoField(primary_key=True, serialize=False)),
                ('jenjang_kelas', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSiswa',
            fields=[
                ('id_siswa', models.AutoField(primary_key=True, serialize=False)),
                ('nisn', models.CharField(max_length=255)),
                ('nama_siswa', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('tempat_lahir', models.CharField(max_length=255)),
                ('tanggal_lahir', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelKelas',
            fields=[
                ('id_kelas', models.AutoField(primary_key=True, serialize=False)),
                ('kode_kelas', models.CharField(max_length=255)),
                ('nama_kelas', models.CharField(max_length=255)),
                ('waktu', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_app.modelguru')),
                ('jenjang_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_app.modeljenjangkelas')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAbsensi',
            fields=[
                ('id_absensi', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_buka', models.DateTimeField()),
                ('tanggal_tutup', models.DateTimeField()),
                ('is_attend', models.BooleanField(default=False)),
                ('gambar_qr', models.ImageField(blank=True, null=True, upload_to='staticfiles/qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_app.modelguru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_app.modelkelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_app.modelsiswa')),
            ],
        ),
    ]
