# Generated by Django 5.0.1 on 2024-01-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelabsensi',
            name='encrypted_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modelabsensi',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
